language: objective-c
osx_image: xcode11.2

branches:
  only:
  - master

script:
  - xcodebuild -project MaterialDesignSpinner.xcodeproj -scheme MaterialDesignSpinner -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build
  - pod lib lint --quick
